### ISSUE TITLE
[suggestion] Ingot blocks/Armor/Tools

### ISSUE THREAD

**Issue by FuuNoKamiOka** [TheOnePath/More-Ores#1]
Doesn't have to be a full crazy thing, but I think adding metal blocks, armor and tools would be great. Right now the mod is kinda lacking in other content and metals just kinda sit there. Would be neat to have more options for more mid to end game thing. Right now there really aren't that many mods in 1.14 that have other ores and options. Adding more would be great, Just kinda my opinion.

**Comment by TheOnePath** [comment]
Hi FuuNoKamiOka,

Thank you for your suggestion for this mod. I apologise for the prolonged response due to studies, but I'm actively working on reworking the mod slightly in how the process of obtaining ingots from the ores for doubling is done. I'm glad to hear your opinion on what you'd potentially like to see from the mod.

I can confirm that I will be implementing new grades of tools, new methods of ore doubling as I mentioned, and hopefully a way of creating alloys but don't hold me to that one coming too soon. I cannot promise that the idea of armor being implemented into this mod but I will take into suggestion for blocks and nuggets, whilst creating ore dictionaries as well.

Since 1.14 has been out for some time now I'm looking at targeting more for 1.15/1.16, however, looking at getting a stable and balanced 1.14 version complete.

(Note, I will leave this issue unclosed till the next release)
